language: php

php:
    - 7.1
    - 7.2
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - cp phpunit.xml.dist phpunit.xml
    - composer self-update
    - composer install --dev
    - pip install --user codecov

script:
    - phpunit -c phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

dist: trusty
